---
output:
  html_document: default
  pdf_document: default
---
```{r}
gucplant_raw<-as.data.frame(read.csv("~/Desktop/Practical Computing /PracCompFinal/MTB_GUC_Plant Measurements_PracComp.csv", header = TRUE))
gucplant <- na.omit(gucplant_raw)
gucplant
```

```{r}
gucplant.Aseries<-as.data.frame(read.csv("~/Desktop/Practical Computing /PracCompFinal/MTB_GUC_Plant Measurements_PracComp-BREWER.csv", header=TRUE))
#install.packages(car)
#library(car)
```

```{r}
#install.packages(c("ggplot2", "ggpubr", "tidyverse", "broom", "AICcmodavg"))
gucplant.Aseries
```


```{r}
#install.packages("ggplot2")
```

```{r}
library(hrbrthemes)
library(ggplot2)

gucplant.Aseries.SL<-ggplot(data=gucplant.Aseries, aes(x=gucplant.Aseries$Tank, y=ShootLength)) +
  geom_point(color="Red", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  ggtitle("Shoot Length for All Tanks")
gucplant.Aseries.SL + theme(axis.text.x = element_text(size=8))
gucplant.Aseries.SL
```



```{r}
gucplant.Aseries.RL<-ggplot(data=gucplant.Aseries, aes(x=gucplant.Aseries$Tank, y=RootLength)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  ggtitle("Root Length by Shoot Length Session 1")
gucplant.Aseries.RL + theme(axis.text.x = element_text(size=8))
gucplant.Aseries.RL
```

```{r}
boxplot(gucplant.Aseries$RootLength ~ gucplant.Aseries$Species)
```

```{r}
boxplot(gucplant.Aseries$ShootLength ~ gucplant.Aseries$Species)
```


```{r}
plot(gucplant.Aseries$RootLength ~ gucplant.Aseries$ShootLength, col=factor(gucplant.Aseries$Species))

Juncus <- gucplant.Aseries[ which(gucplant.Aseries$Species == "Juncus"), ]
Panicum <- gucplant.Aseries[ which(gucplant.Aseries$Species == "Panicum"), ]
Pontederia <- gucplant.Aseries[ which(gucplant.Aseries$Species == "Pontederia"), ]

Juncus.reg <- lm(Juncus$RootLength ~ Juncus$ShootLength)
Panicum.reg <- lm(Panicum$RootLength ~ Panicum$ShootLength)
Pontederia.reg <- lm(Pontederia$RootLength ~ Pontederia$ShootLength)

abline(Juncus.reg, col="black")
abline(Panicum.reg, col="red", lty=2)
abline(Pontederia.reg, col="green", lty=3)
```

```{r}
gucplant.Aseries.ANOVA.S <- aov(gucplant.Aseries$ShootLength ~ gucplant.Aseries$Species)
summary(gucplant.Aseries.ANOVA.S)
```

```{r}
TukeyHSD(gucplant.Aseries.ANOVA.S)
```

```{r}
gucplant.Aseries.ANOVA.R <- aov(gucplant.Aseries$RootLength ~ gucplant.Aseries$Species)
summary(gucplant.Aseries.ANOVA.R)
```

```{r}
TukeyHSD(gucplant.Aseries.ANOVA.R)
```

```{r}
library(ggstatsplot)
library(tidyverse)

plt <- ggbetweenstats(
  data = gucplant.Aseries,
  x = Species,
  y = RootLength,
  ylab = "Root Length"
)

plt
```

```{r}
plt2 <- ggbetweenstats(
  data = gucplant.Aseries,
  x = Species,
  y = ShootLength, 
  ylab="Shoot Length"
)

plt2
```

```{r}
gucplantbytankA1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$A1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankA1s

gucplantbytankA2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$A2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankA2s

gucplantbytankA3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$A3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankA3s

library(ggpubr)
ggarrange(gucplantbytankA1s + rremove("x.text"), gucplantbytankA2s + rremove("x.text"), gucplantbytankA3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```




```{r}
gucplantbytankA1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$A1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankA1r

gucplantbytankA2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$A2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankA2r

gucplantbytankA3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$A3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankA3r

ggarrange(gucplantbytankA1r + rremove("x.text"), gucplantbytankA2r + rremove("x.text"), gucplantbytankA3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankB1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$B1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankB1r

gucplantbytankB2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$B2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankB2r

gucplantbytankB3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$B3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankB3r

ggarrange(gucplantbytankB1r + rremove("x.text"), gucplantbytankB2r + rremove("x.text"), gucplantbytankB3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankB1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$B1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankB1r

gucplantbytankB2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$B2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankB2s

gucplantbytankB3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$B3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankB3s

ggarrange(gucplantbytankB1s + rremove("x.text"), gucplantbytankB2s + rremove("x.text"), gucplantbytankB3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankC1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$C1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankC1r

gucplantbytankC2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$C2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankC2r

gucplantbytankC3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$C3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankC3r

ggarrange(gucplantbytankC1r + rremove("x.text"), gucplantbytankC2r + rremove("x.text"), gucplantbytankC3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankC1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$C1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankC1s

gucplantbytankC2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$C2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankC2s

gucplantbytankC3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$C3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankC3s

ggarrange(gucplantbytankC1s + rremove("x.text"), gucplantbytankC2s + rremove("x.text"), gucplantbytankC3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```
```{r}
gucplantbytankABJ1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABJ1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABJ1r

gucplantbytankABJ2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABJ2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABJ2r

gucplantbytankABJ3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABJ3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABJ3r

ggarrange(gucplantbytankABJ1r + rremove("x.text"), gucplantbytankABJ2r + rremove("x.text"), gucplantbytankABJ3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABJ1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABJ1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABJ1s

gucplantbytankABJ2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABJ2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABJ2s

gucplantbytankABJ3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABJ3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABJ3s

ggarrange(gucplantbytankABJ1s + rremove("x.text"), gucplantbytankABJ2s + rremove("x.text"), gucplantbytankABJ3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABPo1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABPo1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABPo1r

gucplantbytankABPo2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABPo2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABPo2r

gucplantbytankABPo3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABPo3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABPo3r

ggarrange(gucplantbytankABPo1r + rremove("x.text"), gucplantbytankABPo2r + rremove("x.text"), gucplantbytankABPo3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankACJ1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACJ1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACJ1r

gucplantbytankACJ2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACJ2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACJ2r

gucplantbytankACJ3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACJ3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACJ3r

ggarrange(gucplantbytankACJ1r + rremove("x.text"), gucplantbytankACJ2r + rremove("x.text"), gucplantbytankACJ3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankACJ1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACJ1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACJ1s

gucplantbytankACJ2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACJ2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACJ2s

gucplantbytankACJ3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACJ3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACJ3s

ggarrange(gucplantbytankACJ1s + rremove("x.text"), gucplantbytankACJ2s + rremove("x.text"), gucplantbytankACJ3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankACPa1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACPa1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACPa1r

gucplantbytankACPa2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACPa2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACPa2r

gucplantbytankACPa3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACPa3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACPa3r

ggarrange(gucplantbytankACPa1r + rremove("x.text"), gucplantbytankACPa2r + rremove("x.text"), gucplantbytankACPa3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankACPa1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACPa1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACPa1s

gucplantbytankACPa2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACPa2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACPa2s

gucplantbytankACPa3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ACPa3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankACPa3s

ggarrange(gucplantbytankACPa1s + rremove("x.text"), gucplantbytankACPa2s + rremove("x.text"), gucplantbytankACPa3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankBCPa1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPa1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPa1r

gucplantbytankBCPa2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPa2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPa2r

gucplantbytankBCPa3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPa3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPa3r

ggarrange(gucplantbytankBCPa1r + rremove("x.text"), gucplantbytankBCPa2r + rremove("x.text"), gucplantbytankBCPa3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankBCPo1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPo1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPo1r

gucplantbytankBCPo2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPo2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPo2r

gucplantbytankBCPo3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPo3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPo3r

ggarrange(gucplantbytankBCPo1r + rremove("x.text"), gucplantbytankBCPo2r + rremove("x.text"), gucplantbytankBCPo3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankBCPo1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPo1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPo1r

gucplantbytankBCPo2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPo2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPo2s

gucplantbytankBCPo3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$BCPo3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankBCPo3s

ggarrange(gucplantbytankBCPo1s + rremove("x.text"), gucplantbytankBCPo2s + rremove("x.text"), gucplantbytankBCPo3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABCPo1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPo1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPo1r

gucplantbytankABCPo2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPo2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPo2r

gucplantbytankABCPo3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPo3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPo3r

ggarrange(gucplantbytankABCPo1r + rremove("x.text"), gucplantbytankABCPo2r + rremove("x.text"), gucplantbytankABCPo3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABCPo1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPo1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPo1s

gucplantbytankABCPo2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPo2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPo2s

gucplantbytankABCPo3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPo3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPo3s

ggarrange(gucplantbytankABCPo1s + rremove("x.text"), gucplantbytankABCPo2s + rremove("x.text"), gucplantbytankABCPo3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABCPa1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPa1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPa1r

gucplantbytankABCPa2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPa2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPa2r

gucplantbytankABCPa3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPa3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPa3r

ggarrange(gucplantbytankABCPa1r + rremove("x.text"), gucplantbytankABCPa2r + rremove("x.text"), gucplantbytankABCPa3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABCPa1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPa1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPa1s

gucplantbytankABCPa2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPa2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPa2s

gucplantbytankABCPa3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCPa3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCPa3s

ggarrange(gucplantbytankABCPa1s + rremove("x.text"), gucplantbytankABCPa2s + rremove("x.text"), gucplantbytankABCPa3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABCJ1r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCJ1.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCJ1r

gucplantbytankABCJ2r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCJ2.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCJ2r

gucplantbytankABCJ3r <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCJ3.r)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCJ3r

ggarrange(gucplantbytankABCJ1r + rremove("x.text"), gucplantbytankABCJ2r + rremove("x.text"), gucplantbytankABCJ3r + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplantbytankABCJ1s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCJ1.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCJ1s

gucplantbytankABCJ2s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCJ2.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCJ2s

gucplantbytankABCJ3s <- ggplot(data = gucplant, aes(x=gucplant$Date, y=gucplant$ABCJ3.s)) +
  geom_point(color="Blue", linewidth=2, alpha=0.9) +
  theme_ipsum() +
  theme(axis.text.x = element_text(size = 8))
gucplantbytankABCJ3s

ggarrange(gucplantbytankABCJ1s + rremove("x.text"), gucplantbytankABCJ2s + rremove("x.text"), gucplantbytankABCJ3s + rremove("x.text"),
          labels = c("A", "B", "C"), 
          ncol =2, nrow =2)
```

```{r}
gucplant.ANOVA.A.S12 <- aov(gucplant$A1.s ~ gucplant$A2.s)
summary(gucplant.ANOVA.A.S12)
```

```{r}
gucplant.ANOVA.A.S13 <- aov(gucplant$A1.s ~ gucplant$A3.s)
summary(gucplant.ANOVA.A.S13)
```

```{r}
gucplant.ANOVA.A.S23 <- aov(gucplant$A3.s ~ gucplant$A2.s)
summary(gucplant.ANOVA.A.S23)
```

```{r}
gucplant.ANOVA.A.R12 <- aov(gucplant$A1.r ~ gucplant$A2.r)
summary(gucplant.ANOVA.A.R12)
```

```{r}
gucplant.ANOVA.A.R23 <- aov(gucplant$A3.r ~ gucplant$A2.r)
summary(gucplant.ANOVA.A.R23)
```

```{r}
gucplant.ANOVA.A.R13 <- aov(gucplant$A1.r ~ gucplant$A3.r)
summary(gucplant.ANOVA.A.R13)
```

```{r}
gucplant.ANOVA.B.R12 <- aov(gucplant$B1.r ~ gucplant$B2.r)
summary(gucplant.ANOVA.B.R12)
```

```{r}
gucplant.ANOVA.B.R13 <- aov(gucplant$B1.r ~ gucplant$B3.r)
summary(gucplant.ANOVA.B.R13)
```

```{r}
gucplant.ANOVA.B.R23 <- aov(gucplant$B3.r ~ gucplant$B2.r)
summary(gucplant.ANOVA.B.R23)
```

```{r}
gucplant.ANOVA.B.S12 <- aov(gucplant$B1.s ~ gucplant$B2.s)
summary(gucplant.ANOVA.B.S12)
```

```{r}
gucplant.ANOVA.B.S13 <- aov(gucplant$B1.s ~ gucplant$B3.s)
summary(gucplant.ANOVA.B.S13)
```

```{r}
gucplant.ANOVA.B.S23 <- aov(gucplant$B3.s ~ gucplant$B2.s)
summary(gucplant.ANOVA.B.S23)
```

```{r}
gucplant.ANOVA.C.R12 <- aov(gucplant$C1.r ~ gucplant$C2.r)
summary(gucplant.ANOVA.C.R12)
```

```{r}
gucplant.ANOVA.C.R13 <- aov(gucplant$C1.r ~ gucplant$C3.r)
summary(gucplant.ANOVA.C.R13)
```

```{r}
gucplant.ANOVA.C.R23 <- aov(gucplant$C3.r ~ gucplant$C2.r)
summary(gucplant.ANOVA.C.R23)
```

```{r}
gucplant.ANOVA.C.S12 <- aov(gucplant$C1.s ~ gucplant$C2.s)
summary(gucplant.ANOVA.C.S12)
```

```{r}
gucplant.ANOVA.C.S13 <- aov(gucplant$C1.s ~ gucplant$C3.s)
summary(gucplant.ANOVA.C.S13)
```

```{r}
gucplant.ANOVA.C.S23 <- aov(gucplant$C3.s ~ gucplant$C2.s)
summary(gucplant.ANOVA.C.S23)
```

```{r}
gucplant.ANOVA.AB.R12 <- aov(gucplant$ABJ1.r ~ gucplant$ABJ2.r)
summary(gucplant.ANOVA.AB.R12)
```

```{r}
gucplant.ANOVA.AB.R13 <- aov(gucplant$ABJ1.r ~ gucplant$ABJ3.r)
summary(gucplant.ANOVA.AB.R12)
```

```{r}
gucplant.ANOVA.AB.R23 <- aov(gucplant$ABJ3.r ~ gucplant$ABJ2.r)
summary(gucplant.ANOVA.AB.R12)
```

```{r}
gucplant.ANOVA.AB.S12 <- aov(gucplant$ABJ1.s ~ gucplant$ABJ2.s)
summary(gucplant.ANOVA.AB.S12)
```

```{r}
gucplant.ANOVA.AB.S13 <- aov(gucplant$ABJ1.s ~ gucplant$ABJ3.s)
summary(gucplant.ANOVA.AB.S13)
```

```{r}
gucplant.ANOVA.AB.S23 <- aov(gucplant$ABJ3.s ~ gucplant$ABJ2.s)
summary(gucplant.ANOVA.AB.S23)
```

```{r}
gucplant.ANOVA.ABPo.S12 <- aov(gucplant$ABPo1.s ~ gucplant$ABPo2.s)
summary(gucplant.ANOVA.ABPo.S12)
```

```{r}
gucplant.ANOVA.ABPo.S13 <- aov(gucplant$ABPo1.s ~ gucplant$ABPo3.s)
summary(gucplant.ANOVA.ABPo.S13)
```

```{r}
gucplant.ANOVA.ABPo.S23 <- aov(gucplant$ABPo3.s ~ gucplant$ABPo2.s)
summary(gucplant.ANOVA.ABPo.S23)
```

```{r}
gucplant.ANOVA.ABPo.R12 <- aov(gucplant$ABPo1.r ~ gucplant$ABPo2.r)
summary(gucplant.ANOVA.ABPo.R12)
```

```{r}
gucplant.ANOVA.ABPo.R13 <- aov(gucplant$ABPo1.r ~ gucplant$ABPo3.r)
summary(gucplant.ANOVA.ABPo.R13)
```

```{r}
gucplant.ANOVA.ABPo.R23 <- aov(gucplant$ABPo3.r ~ gucplant$ABPo2.r)
summary(gucplant.ANOVA.ABPo.R23)
```

```{r}
gucplant.ANOVA.ACJ.R12 <- aov(gucplant$ACJ1.r ~ gucplant$ACJ2.r)
summary(gucplant.ANOVA.ACJ.R12)
```

```{r}
gucplant.ANOVA.ACJ.R13 <- aov(gucplant$ACJ1.r ~ gucplant$ACJ3.r)
summary(gucplant.ANOVA.ACJ.R13)
```

```{r}
gucplant.ANOVA.ACJ.R23 <- aov(gucplant$ACJ2.r ~ gucplant$ACJ3.r)
summary(gucplant.ANOVA.ACJ.R23)
```

```{r}
gucplant.ANOVA.ACJ.S12 <- aov(gucplant$ACJ1.s ~ gucplant$ACJ2.s)
summary(gucplant.ANOVA.ACJ.S12)
```

```{r}
gucplant.ANOVA.ACJ.S13 <- aov(gucplant$ACJ1.s ~ gucplant$ACJ3.s)
summary(gucplant.ANOVA.ACJ.S13)
```

```{r}
gucplant.ANOVA.ACJ.S23 <- aov(gucplant$ACJ3.s ~ gucplant$ACJ2.s)
summary(gucplant.ANOVA.ACJ.S23)
```

```{r}
gucplant.ANOVA.ACPa.S12 <- aov(gucplant$ACPa1.s ~ gucplant$ACPa2.s)
summary(gucplant.ANOVA.ACPa.S12)
```

```{r}
gucplant.ANOVA.ACPa.S13 <- aov(gucplant$ACPa1.s ~ gucplant$ACPa3.s)
summary(gucplant.ANOVA.ACPa.S13)
```

```{r}
gucplant.ANOVA.ACPa.S23 <- aov(gucplant$ACPa3.s ~ gucplant$ACPa2.s)
summary(gucplant.ANOVA.ACPa.S23)
```

```{r}
gucplant.ANOVA.ACPa.R12 <- aov(gucplant$ACPa1.r ~ gucplant$ACPa2.r)
summary(gucplant.ANOVA.ACPa.R12)
```

```{r}
gucplant.ANOVA.ACPa.R13 <- aov(gucplant$ACPa3.r ~ gucplant$ACPa1.r)
summary(gucplant.ANOVA.ACPa.R13)
```

```{r}
gucplant.ANOVA.ACPa.R23 <- aov(gucplant$ACPa3.r ~ gucplant$ACPa2.r)
summary(gucplant.ANOVA.ACPa.R23)
```

```{r}
gucplant.ANOVA.ABCJ.R12<- aov(gucplant$ABCJ1.r ~ gucplant$ABCJ2.r)
summary(gucplant.ANOVA.ABCJ.R12)
```

```{r}
gucplant.ANOVA.ABCJ.R13<- aov(gucplant$ABCJ1.r ~ gucplant$ABCJ3.r)
summary(gucplant.ANOVA.ABCJ.R13)
```

```{r}
gucplant.ANOVA.ABCJ.R23<- aov(gucplant$ABCJ3.r ~ gucplant$ABCJ2.r)
summary(gucplant.ANOVA.ABCJ.R23)
```

```{r}
gucplant.ANOVA.ABCJ.S12<- aov(gucplant$ABCJ1.s ~ gucplant$ABCJ2.s)
summary(gucplant.ANOVA.ABCJ.S12)
```

```{r}
gucplant.ANOVA.ABCJ.S13<- aov(gucplant$ABCJ1.s ~ gucplant$ABCJ3.s)
summary(gucplant.ANOVA.ABCJ.R12)
```

```{r}
gucplant.ANOVA.ABCJ.S23<- aov(gucplant$ABCJ3.s ~ gucplant$ABCJ2.s)
summary(gucplant.ANOVA.ABCJ.S23)
```

```{r}
gucplant.ANOVA.ABCPo.R12 <- aov(gucplant$ABCPo1.r ~ gucplant$ABCPo2.r)
summary(gucplant.ANOVA.ABCPo.R12)
```

```{r}
gucplant.ANOVA.ABCPo.R13 <- aov(gucplant$ABCPo1.r ~ gucplant$ABCPo3.r)
summary(gucplant.ANOVA.ABCPo.R13)
```

```{r}
gucplant.ANOVA.ABCPo.R23 <- aov(gucplant$ABCPo2.r ~ gucplant$ABCPo3.r)
summary(gucplant.ANOVA.ABCPo.R23)
```

```{r}
gucplant.ANOVA.ABCPo.S12 <- aov(gucplant$ABCPo1.s ~ gucplant$ABCPo3.s)
summary(gucplant.ANOVA.ABCPo.S12)
```

```{r}
gucplant.ANOVA.ABCPo.S13 <- aov(gucplant$ABCPo1.s ~ gucplant$ABCPo3.s)
summary(gucplant.ANOVA.ABCPo.S13)
```

```{r}
gucplant.ANOVA.ABCPo.S23 <- aov(gucplant$ABCPo2.s ~ gucplant$ABCPo3.s)
summary(gucplant.ANOVA.ABCPo.S23)
```

```{r}
gucplant.ANOVA.ABCPa.R12 <- aov(gucplant$ABCPa1.r ~ gucplant$ABCPa2.r)
summary(gucplant.ANOVA.ABCPa.R12)
```

```{r}
gucplant.ANOVA.ABCPa.R13 <- aov(gucplant$ABCPa1.r ~ gucplant$ABCPa3.r)
summary(gucplant.ANOVA.ABCPa.R13)
```

```{r}
gucplant.ANOVA.ABCPa.R23 <- aov(gucplant$ABCPa3.r ~ gucplant$ABCPa2.r)
summary(gucplant.ANOVA.ABCPa.R23)
```

```{r}
gucplant.ANOVA.ABCPa.S13 <- aov(gucplant$ABCPa1.s ~ gucplant$ABCPa2.s)
summary(gucplant.ANOVA.ABCPa.S13)
```

```{r}
gucplant.ANOVA.ABCPa.S13 <- aov(gucplant$ABCPa1.s ~ gucplant$ABCPa3.s)
summary(gucplant.ANOVA.ABCPa.S13)
```

```{r}
gucplant.ANOVA.ABCPa.S23 <- aov(gucplant$ABCPa2.s ~ gucplant$ABCPa3.s)
summary(gucplant.ANOVA.ABCPa.S23)
```

```{r}
gucplant.ANOVA.AB1.R <- aov(gucplant$A1.r ~ gucplant$B1.r)
summary(gucplant.ANOVA.AB1.R)
```

```{r}
gucplant.ANOVA.AC1.R <- aov(gucplant$A1.r ~ gucplant$C1.r)
summary(gucplant.ANOVA.AC1.R)
```

```{r}
gucplant.ANOVA.AB2.R <- aov(gucplant$A2.r ~ gucplant$B2.r)
summary(gucplant.ANOVA.AB2.R)
```

```{r}
gucplant.ANOVA.AC2.R <- aov(gucplant$A2.r ~ gucplant$C2.r)
summary(gucplant.ANOVA.AC2.R)
```

```{r}
gucplant.ANOVA.AB3.R <- aov(gucplant$A3.r ~ gucplant$B3.r)
summary(gucplant.ANOVA.AB3.R)
```

```{r}
gucplant.ANOVA.AC3.R <- aov(gucplant$A3.r ~ gucplant$C3.r)
summary(gucplant.ANOVA.AC3.R)
```

```{r}
gucplant.ANOVA.AB1.S <- aov(gucplant$A1.s ~ gucplant$B1.s)
summary(gucplant.ANOVA.AB1.S)
```

```{r}
gucplant.ANOVA.AB2.S <- aov(gucplant$A2.s ~ gucplant$B2.s)
summary(gucplant.ANOVA.AB2.S)
```

```{r}
gucplant.ANOVA.AB3.S <- aov(gucplant$A3.s ~ gucplant$B3.s)
summary(gucplant.ANOVA.AB3.S)
```

```{r}
gucplant.ANOVA.AC1.S <- aov(gucplant$A1.s ~ gucplant$C1.s)
summary(gucplant.ANOVA.AC1.S)
```

```{r}
gucplant.ANOVA.AC2.S <- aov(gucplant$A2.s ~ gucplant$C2.s)
summary(gucplant.ANOVA.AC2.S)
```

```{r}
gucplant.ANOVA.AC3.S <- aov(gucplant$A3.s ~ gucplant$C3.s)
summary(gucplant.ANOVA.AC3.S)
```

```{r}
gucplant.ANOVA.BC1.S <- aov(gucplant$B1.s ~ gucplant$C1.s)
summary(gucplant.ANOVA.BC1.S)
```

```{r}
gucplant.ANOVA.BC2.S <- aov(gucplant$B2.s ~ gucplant$C2.s)
summary(gucplant.ANOVA.BC2.S)
```

```{r}
gucplant.ANOVA.BC3.S <- aov(gucplant$B3.s ~ gucplant$C3.s)
summary(gucplant.ANOVA.BC3.S)
```

```{r}
gucplant.ANOVA.BC1.R <- aov(gucplant$B1.r ~ gucplant$C1.r)
summary(gucplant.ANOVA.BC1.R)
```

```{r}
gucplant.ANOVA.BC2.R <- aov(gucplant$B2.r ~ gucplant$C2.r)
summary(gucplant.ANOVA.BC2.R)
```

```{r}
gucplant.ANOVA.BC3.R <- aov(gucplant$B3.r ~ gucplant$C3.r)
summary(gucplant.ANOVA.BC3.R)
```








